[package]
name = "glashatay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
argh = "0.1.12"
log = "0.4.20"
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
simple_logger = "4.3.3"
teloxide = { version = "0.12.2", features = ["macros"] }
tokio = { version = "1.35.1", features = ["full"] }
url = "2.5.0"
